 dir.create("data")
dir.create("script")
dir.create("results")
dir.create("clean_data")
str(patient_info)
summary(patient_info)
sapply(patient_info, class)
patient_info$gender<- as.factor(patient_info$gender)
patient_info$diagnosis<- as.factor(patient_info$diagnosis)
patient_info$smoker<- as.factor(patient_info$smoker)
sapply(patient_info, class)
patient_info$smoker_binary <- ifelse(patient_info$smoker=="Yes",1,0)
patient_info$smoker_binary <- as.factor(patient_info$smoker_binary)
head(patient_info[, c("smoker","smoker_binary")])
write.csv(patient_info, "clean_data/patient_info_clean.csv")
